### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ddslick' of null

### ISSUE THREAD

**Issue by micker** [jsmodules/ddslick#17]
hello i try to add ddslick in my form ..
1 i add library
2 i add select sample
`<select id="select-marker">
        <option value="0" data-imagesrc="http://i.imgur.com/XkuTj3B.png"
            data-description="Description with Facebook">Facebook</option>
        <option value="1" data-imagesrc="http://i.imgur.com/8ScLNnk.png"
            data-description="Description with Twitter">Twitter</option>
        <option value="2" selected="selected" data-imagesrc="http://i.imgur.com/aDNdibj.png"
            data-description="Description with LinkedIn">LinkedIn</option>
        <option value="3" data-imagesrc="http://i.imgur.com/kFAk2DX.png"
            data-description="Description with Foursquare">Foursquare</option>
    </select>`

`jQuery(document).ready(function() {
	$("#select-marker").ddslick({
    onSelected: function(selectedData){
        //callback function: do something with selectedData;
	}	
});
	});`
the error is Uncaught TypeError: Cannot read property 'ddslick' of null
some idea ?

**Comment by micker** [comment]
somebody ?

**Comment by oizulain** [comment]
You invoke jQuery using "jQuery" and you then invoke jQuery using "$", I'm guessing jQuery is not available as "$" in your page? 

Try:
`jQuery("#select-marker").ddslick({ onSelected: function(selectedData){ //callback function: do something with selectedData; }	}); });`

This does not look like a ddslick issue anyway, so I'm closing
