### ISSUE TITLE
Q: Which version(s) of jQuery are dependencies

### ISSUE THREAD

**Issue by mwpowellhtx** [jsmodules/ddslick#3]
Need to know which version(s) of jQuery (and/or jQuery UI) are dependencies.

**Comment by oizulain** [comment]
jQuery >= 1.7.2 / No need for jQuery UI

**Comment by mwpowellhtx** [comment]
I'd like to clarify, that's "greater than", and not "greater than or equal to"? Thanks!

**Edit**: Oh, never mind. I see the ">=", but this did not come through the email for some reason.

**Comment by oizulain** [comment]
@mwpowellhtx - You are right, I edited the comment because I forgot the "="

It might work even with versions previous to 1.7.2, but I haven't tested

**Comment by mwpowellhtx** [comment]
@oizulain Fair enough; considering jQuery is version 1.10.2 (minimum) that I am using, probably far advanced from there, I just need to establish some reasonably historic baseline dependency. Thanks again!

**Comment by mwpowellhtx** [comment]
The project [`package.json`](http://github.com/jsmodules/ddslick/blob/master/package.json#L28) indicates:

``` JSON
{
  "dependencies": {
    "jquery": "^2.1.4"
  }
}
```

Now, I don't mind upgrading my jQuery dependencies, if necessary and at all possible, using NuGet sources, but I'd like to understand that better, if you don't mind.
