### ISSUE TITLE
selectText shows up as a dd-selected anchor

### ISSUE THREAD

**Issue by mwpowellhtx** [jsmodules/ddslick#5]
This might have to do with an unwritten dependency on ddslick CSS, but the selectText shows up as an anchor url, and I don't want it to, that would be inappropriate. If just needs to be shown as text, bold or not, or ability to specify a class, in either event, etc, etc.

For what its worth, the [demo](http://designwithpc.com/Plugins/ddSlick#demo) doesn't do this.

Thoughts?

**Comment by oizulain** [comment]
You must have had some CSS rule on your page applying the anchor style to the selector.
