### ISSUE TITLE
Repeated expanding and collapsing grows the item heights

### ISSUE THREAD

**Issue by mwpowellhtx** [jsmodules/ddslick#6]
Not sure why that is happening, but methinks that the item heights should be left alone once established.

Also for what it's worth, the [demo](http://designwithpc.com/Plugins/ddSlick#demo) does not do this.

**Comment by mwpowellhtx** [comment]
It's actually worse than that; inspecting with Google Chrome, both expanding and collapsing both upset the line-height style.

**Comment by mwpowellhtx** [comment]
Which (sort of) translates over into a selected item; not the growing part, but a larger line height than the original selectText.

**Comment by mwpowellhtx** [comment]
According to at least [one post](http://designwithpc.com/Plugins/ddSlick#post-1596060340) (you may need to expand it to find it, not sure that I have the Url quite right to land on it), this may be because of a clash with Bootstrap, which I also have loading. Not sure what that clash could be, but it would be helpful to re-factor the CSS into a separate file that is less hard-coded into the code itself; as either part of this issue, or as a follow on.

**Comment by oizulain** [comment]
@mwpowellhtx I don't see how this could be a bug on ddslick, have you been able to find out the cause since you created the issue? Can you reproduce it removing the dependencies that might be causing the issue?

**Comment by mwpowellhtx** [comment]
@oizulain Hello, and thanks for considering my feedback. Unfortunately, the conflict here, presumably between something in `Bootstrap`, which is fairly common to conflict with it seems, and `ddslick` is more of a rabbit hole than I dare to pursue at the moment. If time permits and I feel adventurous enough, I may revisit it, but I can't promise it at the moment.  Which means while cool, the issue is a show stopper for usability at the moment.

**Comment by oizulain** [comment]
@mwpowellhtx I'm curious, can you provide more info on how I could reproduce the issue? I.e. version of Bootstrap, additional dependencies?

**Comment by mwpowellhtx** [comment]
Sure,

Here's my header includes:

```
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kickoff - My ASP.NET Application</title>
    <link href="/Content/bootstrap.css" rel="stylesheet">
    <link href="/Content/site.css" rel="stylesheet">
    <link href="/Content/themes/base/all.css" rel="stylesheet">
    <script src="/Scripts/jquery-1.10.2.js"></script>
    <script src="/Scripts/bootstrap.js"></script>
    <script src="/Scripts/respond.js"></script>
    <script src="/Scripts/jquery-ui-1.11.4.js"></script>
    <script src="/Scripts/jquery.validate.js"></script>
    <script src="/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="/Scripts/PepJS/pep-0.4.1.js"></script>
    <script src="/Scripts/ExtensionsJS/str-1.1.0.js"></script>
    <script src="/Scripts/ExtensionsJS/arr-1.2.0.js"></script>
    <script src="/Scripts/ExtensionsJS/boolean-1.0.0.js"></script>
    <script src="/Scripts/ExtensionsJS/math-1.0.0.js"></script>
    <script src="/Scripts/poly2tri.js"></script>
    <script src="/Scripts/Oimo.js"></script>
    <script src="/Scripts/babylon.max.js"></script>
    <script src="/Scripts/uuid.js"></script>
    <script src="/Scripts/FootballJS/element-1.2.0.js"></script>
    <script src="/Scripts/FootballJS/goalpost-1.1.0.js"></script>
    <script src="/Scripts/FootballJS/gridiron-1.4.0.js"></script>
    <script src="/Scripts/modernizr-2.6.2.js"></script>
</head>
```

For dependencies, NuGet, that I know of:
- bootstrap 3.0.0 (jquery >= 1.9.0)
- jquery 1.10.2

**Comment by oizulain** [comment]
Couldn't reproduce the issue with `bootstrap 3.0.0` and `jquery 1.10.2`
