### ISSUE TITLE
Setting val() does not change the shown item

### ISSUE THREAD

**Issue by mwpowellhtx** [jsmodules/ddslick#7]
I can get or set the val() just fine, in and of itself, it seems. However, the displayed item does not change as a result of val having been set.

**Comment by oizulain** [comment]
The method to set is: 
`$('#demoSetSelected').ddslick('select', {index: i });`

You can also set it by value:
`$('#demoSetSelected').ddslick('select', {id: value });`

**Comment by mwpowellhtx** [comment]
Index does not do my any good, at least not in this use case.

`{ id: value }` is inconsistent with the protocol that was used to populate the drop down items in the first place. Strongly suggest `{ value: value }`.
