### ISSUE TITLE
Suggest selecting value for value not id for value

### ISSUE THREAD

**Issue by mwpowellhtx** [jsmodules/ddslick#9]
`id` is `id`, not `value`; furthermore, that is inconsistent with the protocol used to populate the drop down items in the first place.

Should be: `{ value: value }`.

The alternative, `{ index: i }` is fine, but is not necessary for my use cases.

Thank you...

**Comment by oizulain** [comment]
I agree, the selection by `id` will be kept for backwards compatibility, but the selection by `value` has been added and will be available once 1.0.3 is released
